### ISSUE TITLE
Building the project with Leiningen 2.8.1 fails

### ISSUE THREAD

**Issue by jgrodziski** [roomkey/lein-v#13]
Leiningen has now a strict policy on using unsecure maven repository (not using https) and fails with 
```
Tried to use insecure HTTP repository without TLS.
This is almost certainly a mistake; however in rare cases where it's
intentional please see `lein help faq` for details.
```
The repo "http://rk-maven-public.s3-website-us-east-1.amazonaws.com/releases/" don't have an https version, could you please see if adding a certificate is possible? and update the project.clj accordingly?

**Comment by cch1** [comment]
I've updated the repositories to no longer reference the (obsolete) insecure repos.
