### ISSUE TITLE
Document assert-anchored

### ISSUE THREAD

**Issue by rymndhng** [roomkey/lein-v#15]
I noticed that this is something lein-v has available. Is there a particular reason why this isn't advertised as a feature? (In the README and under lein v help)

**Comment by cch1** [comment]
Nope -that's an oversight.  A PR would be welcome.

**Comment by rymndhng** [comment]
Sweet, I'll look into it!

**Comment by cch1** [comment]
Hang tight... I've almost got is resolved.

**Comment by rymndhng** [comment]
very nice 👌
