### ISSUE TITLE
Migrating over from regular leiningen version is clunky

### ISSUE THREAD

**Issue by rymndhng** [roomkey/lein-v#16]
For folks who want to migrate over, this is a bit of a stumbling block if their app is already versioned, because `lein update` will think you're still on version v0.0.0

I had to seed the initial state by manually creating a tag for the first version. 

```
git tag --annotate --message "Automated lein-v release" v1.3.12
```

**Comment by cch1** [comment]
I can see how this is an issue, but I don't have a great "automated" solution.  I think your solution is optimal.

**Comment by rymndhng** [comment]
I can submit a PR to improve the README, it'd probably help folks who want to hop onto this ;)

**Comment by cch1** [comment]
Great.  I'll look forward to it.
