### ISSUE TITLE
Code isn't published to public Maven repo

### ISSUE THREAD

**Issue by code-ape** [roomkey/lein-v#4]
I went to try out lein-v (it looks super handy) and added it to my plugin dependencies only to find the following error:

```bash
$ lein install
Could not find artifact com.roomkey:lein-v:jar:6.1.0 in central (https://repo1.maven.org/maven2/)
Could not find artifact com.roomkey:lein-v:jar:6.1.0 in clojars (https://clojars.org/repo/)
```

I know I can just clone and install it but I was wondering if there was any reason why there is no public publishing of the build for it? I would think that having such a thing would help with adoption.

Cheers,
code-ape

**Comment by cch1** [comment]
Can you provide a copy of your `project.clj` and any significant info from your profile?  If I do `lein new x` and tweak `project.clj` to add the `lein-v` plugin, it works for me.  Here is my resulting `project.clj`:
```
(defproject x "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :plugins [[com.roomkey/lein-v "6.1.0"]]
  :dependencies [[org.clojure/clojure "1.8.0"]])
```

It's possible something is messed up with Clojars, but if so, I can't find it.  Please provide the complete output from running `lein v` after you have modified `project.clj`.  Here is what you should see:
```
[cch1@cch:~/Development/x]$ lein v
Retrieving com/roomkey/lein-v/6.1.0/lein-v-6.1.0.pom from clojars
Retrieving com/roomkey/lein-v/6.1.0/lein-v-6.1.0.jar from clojars
fatal: Not a git repository (or any of the parent directories): .git

Effective version: 0.1.0-SNAPSHOT, SCM workspace state: null
```

**Comment by code-ape** [comment]
@cch1 looks like something was wrong with my local Maven repo. Removed everything pertaining to `lein-v`, tried again, and it worked. Sorry for the false alarm!
